version: "3"

services:
  ckan-dev:
    container_name: ckan
    build:
      context: ckan/
      dockerfile: Dockerfile.dev
      args:
        - TZ=${TZ}
    env_file:
      - .env
    depends_on:
      - db-dev
      - solr-dev
      - redis
      - datapusher
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ./src:/srv/app/src_extensions
      - ckan_storage_dev:/var/lib/ckan
    
  datapusher:
    container_name: datapusher
    build:
      context: datapusher/
    ports:
      - "8800:8800"

  db-dev:
    container_name: db
    env_file:
      - .env
    build:
      context: postgresql/
      args:
        - BASE_IMAGE=${DB_BASE_IMAGE}
    volumes:
      - pg_data_dev:/var/lib/postgresql/data

  solr-dev:
    container_name: solr
    build:
      context: solr/
    ports:
      - "8983:8983"
    volumes:
      - solr_data_dev:/opt/solr/server/solr/ckan/data/

  redis:
    container_name: redis
    image: redis:alpine

volumes:
  ckan_storage_dev:
  pg_data_dev:
  solr_data_dev:
